### ISSUE TITLE
Mi4 LTE

### ISSUE THREAD

**Issue by Mainframe25** [ingbrzy/MA-XML-6.0-PORTUGUESE#8] opened 2015-06-14 10:15 UTC
Hi,

What rom should i use with mi xiaomi Mi4 LTE to have 4G network?

Best regards,

**Comment by Mainframe25** [comment] 2015-07-05 12:54
Dear Mr. Ingbrzy,
I first have to tell you that I appreciate your work very much
Still regarding this issue for mi LTE Mi4, I think the work is not done yet.
I can see that now I have on “Settings - Mobile network settings - Preferred network type”, the LTE network choose option, but when LTE is  enabled, in the top left corner, I still only have the "3G" indication, and for the speed of the network, I think that is not 4G network also.
I send you a picture in attached to try to explain better what I’m talking about.
Thanks for all the support,

Best regards
![screenshot_2015-07-05-13-49-18](https://cloud.githubusercontent.com/assets/12008021/8511782/678bd6aa-231d-11e5-9db1-c045333ac84a.png)

**Comment by ingbrzy** [comment] 2015-07-05 13:05
Are you sure that your carrier supports LTE bands which your Mi4 got?

**Comment by Mainframe25** [comment] 2015-07-05 19:50
Dear Ingbrzy, 

The carrier supports 4g network in other phones,
like iPhone 6 for example. 

Have you got any more specific details
about mi4 LTE bands in order that I can investigate? 

Thanks for the
help 

Best Regards 

Xavier Prozil 

Em 2015-07-05 14:05, ingbrzy
escreveu: 

> Are you sure that your carrier supports LTE bands which
your Mi4 got? 
> 
> --
> Reply to this email directly or view it on
GitHub [1].

 

Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-118619052

**Comment by ingbrzy** [comment] 2015-07-06 03:58
4G Network: FDD-LTE: Band 1/3, TDD-LTE: Band 41
3G network: WCDMA: 850/900/1900 / 2100MHz
2G Network: GSM: 850/900/1800 / 1900MHz
Data Service: GPRS / EDGE / 1x / WCDMA / EVDO / FDD-LTE / TDD-LTE

**Comment by Mainframe25** [comment] 2015-07-15 12:45
Dear Ingbrzy, 

The operator has just confirmed that he operates on
that bands. 

Best regards 

Em 2015-07-06 04:58, ingbrzy escreveu: 

>
4G Network: FDD-LTE: Band 1/3, TDD-LTE: Band 41
> 3G network: WCDMA:
850/900/1900 / 2100MHz
> 2G Network: GSM: 850/900/1800 / 1900MHz
> Data
Service: GPRS / EDGE / 1x / WCDMA / EVDO / FDD-LTE / TDD-LTE 
> 
> --
>
Reply to this email directly or view it on GitHub [1].




Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-118707402

**Comment by KcNirvana** [comment] 2015-07-15 13:09
Hello Mainframe25,
Watch ou for the LTE bands of MI4 and the LTE Bands in Portugal.
The normal bands for LTE international are:
LTE band 1(2100), 3(1800), 5(850), 7(2600), 8(900), 20(800)
and the MI4 LTE only have band 1(2100) and 3(1800).
Are you in a zone that has full LTE support like the center of Lisbon or the center of Porto?

Regards

**Comment by Mainframe25** [comment] 2015-07-15 13:58
I live in center of Porto 

ReRegards 

Em 2015-07-15 14:09,
KcNirvana escreveu: 

> Hello Mainframe25,
> Watch ou for the LTE bands
of MI4 and the LTE Bands in Portugal.
> The normal bands for LTE
international are:
> LTE band 1(2100), 3(1800), 5(850), 7(2600), 8(900),
20(800)
> and the MI4 LTE only have band 1(2100) and 3(1800).
> Are you
in a zone that has full LTE support like the center of Lisbon or the
center of Porto? 
> 
> Regards 
> 
> --
> Reply to this email directly
or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-121609911

**Comment by KcNirvana** [comment] 2015-07-15 14:04
Hello,
Can you go to dial and enter this code *#*#4636#*#* 
Then in phone information you will see the type of network that you are using.
On set preferred network type can you confirm that you have LTE,GSM/WCDMA?
Thank you

**Comment by Mainframe25** [comment] 2015-07-15 16:54
Hi, 

When I do ##4636##, the error I sent you in the picture in
attached is presented and nothing happens. 

Best regards, 

Em
2015-07-15 15:04, KcNirvana escreveu: 

> Hello,
> Can you go to dial
and enter this code _#_#4636#_#_ 
> Then in phone information you will
see the type of network that you are using.
> On set preferred network
type can you confirm that you have LTE,GSM/WCDMA?
> Thank you 
> 
> --
>
Reply to this email directly or view it on GitHub [1].




Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-121625494

**Comment by KcNirvana** [comment] 2015-07-15 17:02
Hello,
Sorry but the code is not ##4636##, don't know why it passed like that.
In portuguese:
Asterisco cardinal asterico cardinal 4636 Cardinal asterisco cardinal asterisco.
Try that please.
Thank you

**Comment by ingbrzy** [comment] 2015-07-15 17:06
code is 
```
*#*#4636#*#*
```

**Comment by Mainframe25** [comment] 2015-07-15 17:17
OK, now it worked :) 

I got the information in attached or 

Best
regards 

Em 2015-07-15 18:02, KcNirvana escreveu: 

> Hello,
> Sorry
but the code is not ##4636##, don't know why it passed like that.
> In
portuguese:
> Asterisco cardinal asterico cardinal 4636 Cardinal
asterisco cardinal asterisco.
> Try that please.
> Thank you 
> 
> --
>
Reply to this email directly or view it on GitHub [1].




Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-121680333

**Comment by Mainframe25** [comment] 2015-07-15 17:19
> OK, now it worked :) 
> 
> I got the information in attached or 
>

> Best regards 
> 
> Em 2015-07-15 18:02, KcNirvana escreveu: 
> 
>>
Hello,
>> Sorry but the code is not ##4636##, don't know why it passed
like that.
>> In portuguese:
>> Asterisco cardinal asterico cardinal
4636 Cardinal asterisco cardinal asterisco.
>> Try that please.
>> Thank
you 
>> 
>> --
>> Reply to this email directly or view it on GitHub
[1].

 

Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-121680333

**Comment by KcNirvana** [comment] 2015-07-15 17:54
Hello, 
I cant see the annex but since this is not a bug related to pt-pt translation I will close the issue.
I recomend that you post your bug in xiaomi.eu forum where more people can help you with that.
Regards

**Closed by KcNirvana** 2015-07-15 17:54 UTC

**Comment by Mainframe25** [comment] 2015-07-15 18:59
Hello, 

I sent you again the picture for the *#*#4636#*#* result


Thanks for the help, 

Best regards 

Em 2015-07-15 18:54, KcNirvana
escreveu: 

> Hello, 
> I cant see the annex but since this is not a bug
related to pt-pt translation I will close the issue.
> I recomend that
you post your bug in xiaomi.eu forum where more people can help you with
that.
> Regards 
> 
> --
> Reply to this email directly or view it on
GitHub [1].

 

Links:
------
[1]
https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/issues/8#issuecomment-121692731
